# These are supported funding model platforms

github: [PabiGamito] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
issuehunt: pabigamito # Replace with a single IssueHunt username
