# These are supported funding model platforms

github: [PabiGamito] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
issuehunt: Line-Numbers-for-Google-Docs/chrome-extension
